<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
    - The basic component of a neural net. It is where an input (initial input, or from the prior layer) and weight are multiplied. Said differently, it is an element in each layer's calculation of the activation function.
- **Input Layer:** 
    - As the name would suggest, they are the inputs... It is the first layer of 'net. There is no function or computation being performed in the input layer. From lecture: "Typically node maps are drawn with one input node for each of the different inputs/features/columns of our dataset, that will be passed into the network."

- **Hidden Layer:**
    - The layers which are performing intermediate computations. We don't directly interact with them. 
- **Output Layer:**
    - This is the final layer of the neural net. This is where we access some output vector. The equivalent of a y_pred from earlier units.
- **Activation:**
    - It's the function that occurs at each node in the network. It forces the value of the node down to a (typically if not always(..?) 0.0 through 1.0 value which determines whether or not the node is activated or not. From lecture, "... they are sometimes referred to as transfer functions because they determine how much signal is transferred to the next layer."
- **Backpropagation:**
    - It is the backward propagation of errors. It is the method by which weights are reversed and updated in each epoch of the neural net.


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [31]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [32]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [33]:
import numpy as np
X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values
y = np.reshape(y,(-1,1))

In [34]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [35]:
X.shape

(10000, 2)

In [36]:
weights = 2 * np.random.random((2,1)) - 1

In [37]:
weighted_sum = np.dot(X, weights)
weighted_sum

array([[0.3278272 ],
       [0.33390702],
       [0.3278272 ],
       ...,
       [0.3278272 ],
       [0.3278272 ],
       [0.33390702]])

In [38]:
y

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [39]:
bias = 1

In [40]:
for iteration in range(1):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(X, weights) + bias
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = y - activated_output
#     print(y.shape), print(activated_output.shape)
    adjustments = error * sigmoid_derivative(activated_output)
#     print(error.shape), print(activated_output.shape)
#     print(adjustments.shape)
#     Update the Weights
    weights += np.dot(X.T, adjustments)
    
    bias += error
        
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-329.51210898]
 [-329.07424731]]
Output after training
[[0.790481  ]
 [0.79148617]
 [0.790481  ]
 ...
 [0.790481  ]
 [0.790481  ]
 [0.79148617]]


### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset.

In [66]:
class NeuralNetwork:
    def __init__(self):
        # Set up Architecture of Neural Network
        self.inputs = 2
        self.hiddenNodes = 3
        self.outputNodes = 1

        # Initial Weights
        # 2x3 Matrix Array for the First Layer
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes) + 1
       
        # 3x1 Matrix Array for Hidden to Output
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) + 1
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        aka "predict"
        """
        
        # Weighted sum of inputs => hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
        
    def backward(self, X,y,o):
        """
        Backward propagate through the network
        """
        
        # Error in Output
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        # How far off are we in relation to the Sigmoid f(x) of the output
        # ^- aka hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        # How much of that "far off" can explained by the input => hidden
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights (input => hidden)
        self.weights1 += X.T.dot(self.z2_delta)
        # Adjustment to second set of weights (hidden => output)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)

In [67]:
# Train my 'net
nn = NeuralNetwork()

# Number of Epochs / Iterations
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.96266602]
 [0.9700926 ]
 [0.96266602]
 ...
 [0.96266602]
 [0.96266602]
 [0.9700926 ]]
Loss: 
 0.4382484594047015
+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[3.14274699e-51]
 [1.77336445e-58]
 [3.14274699e-51]
 ...
 [3.14274699e-51]
 [3.14274699e-51]
 [1.77336445e-58]]
Loss: 
 0.5
+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[3.14274699e-51]
 [1.77336445e-58]
 [3.14274699e-51]
 ...
 [3.14274699e-51]
 [3.14274699e-51]
 [1.77336445e-58]]
Loss: 
 0.5
+---------EPOCH 4---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 


P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.


In [41]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
264   54    1   0       110   206    0        0      108      1      0.0   
60    71    0   2       110   265    1        0      130      0      0.0   
140   51    0   2       120   295    0        0      157      0      0.6   
28    65    0   2       140   417    1        0      157      0      0.8   
136   60    0   2       120   178    1        1       96      0      0.0   

     slope  ca  thal  target  
264      1   1     2       0  
60       2   1     2       1  
140      2   0     2       1  
28       2   1     2       1  
136      2   0     2       1

In [42]:
feats = list(df)[:-1]

In [46]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
264   54    1   0       110   206    0        0      108      1      0.0   
60    71    0   2       110   265    1        0      130      0      0.0   
140   51    0   2       120   295    0        0      157      0      0.6   
28    65    0   2       140   417    1        0      157      0      0.8   
136   60    0   2       120   178    1        1       96      0      0.0   

     slope  ca  thal  target  
264      1   1     2       0  
60       2   1     2       1  
140      2   0     2       1  
28       2   1     2       1  
136      2   0     2       1

In [47]:
X_2 = df[feats].values
X_2 = X_2 / np.amax(X_2, axis=0)
y_2 = df['target'].values
y_2 = np.reshape(y_2,(-1,1))

In [49]:
y_2.shape

(303, 1)

In [50]:
X_2.shape

(303, 13)

In [54]:
model = Sequential()
model.add(Dense(1,input_dim=13, activation='relu'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_2,y_2, epochs=5)

Train on 303 samples
Epoch 1/5
303/303 [==============================] - 1s 3ms/sample - loss: 5.7696 - accuracy: 0.4356
Epoch 2/5
303/303 [==============================] - 0s 77us/sample - loss: 5.4469 - accuracy: 0.4290
Epoch 3/5
303/303 [==============================] - 0s 72us/sample - loss: 5.1882 - accuracy: 0.4224
Epoch 4/5
303/303 [==============================] - 0s 65us/sample - loss: 4.9259 - accuracy: 0.4191
Epoch 5/5
303/303 [==============================] - 0s 68us/sample - loss: 4.7018 - accuracy: 0.4125


In [ ]:
# Baseline model has an accuracy below 50%

In [56]:
# fix random seed for reproducibility
seed = 132
np.random.seed(seed)

# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(32, input_dim=13, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=True)

# define the grid search parameters
param_grid = {'batch_size': [10, 20, 40, 60, 80, 100],
              'epochs': [20]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_2, y_2)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Train on 202 samples
Epoch 1/20
202/202 [==============================] - 1s 3ms/sample - loss: 0.7060 - accuracy: 0.4109
Epoch 2/20
202/202 [==============================] - 0s 148us/sample - loss: 0.6809 - accuracy: 0.6089
Epoch 3/20
202/202 [==============================] - 0s 154us/sample - loss: 0.6585 - accuracy: 0.6832
Epoch 4/20
202/202 [==============================] - 0s 154us/sample - loss: 0.6363 - accuracy: 0.7178
Epoch 5/20
202/202 [==============================] - 0s 160us/sample - loss: 0.6159 - accuracy: 0.7228
Epoch 6/20
202/202 [==============================] - 0s 163us/sample - loss: 0.5960 - accuracy: 0.7723
Epoch 7/20
202/202 [==============================] - 0s 177us/sample - loss: 0.5774 - accuracy: 0.8020
Epoch 8/20
202/202 [==============================] - 0s 170us/sample - loss: 0.5602 - accuracy: 0.7871
Epoch 9/20
202/202 [==============================] - 0s 158us/sample - loss: 0.5454 - accuracy: 0.7723
Epoch 10/20
202/202 [========================

In [57]:
# batch_size of 10 on 20 epochs appears to be the best, now I'll try again with a few different number of epochs. Then with a couple more
# hidden layers in the next iteration.

# fix random seed for reproducibility
seed = 132
np.random.seed(seed)

# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(32, input_dim=13, activation='relu'))
#     model.add(Dense(32, activation='relu'))
#     model.add(Dense(32, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=True)

# define the grid search parameters
param_grid = {'batch_size': [10],
              'epochs': [20, 30, 40, 50]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_2, y_2)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 


Train on 202 samples
Epoch 1/20
202/202 [==============================] - 0s 2ms/sample - loss: 0.7846 - accuracy: 0.4554
Epoch 2/20
202/202 [==============================] - 0s 168us/sample - loss: 0.7193 - accuracy: 0.4802
Epoch 3/20
202/202 [==============================] - 0s 172us/sample - loss: 0.6906 - accuracy: 0.5495
Epoch 4/20
202/202 [==============================] - 0s 178us/sample - loss: 0.6675 - accuracy: 0.5545
Epoch 5/20
202/202 [==============================] - 0s 172us/sample - loss: 0.6487 - accuracy: 0.6733
Epoch 6/20
202/202 [==============================] - 0s 170us/sample - loss: 0.6277 - accuracy: 0.7327
Epoch 7/20
202/202 [==============================] - 0s 166us/sample - loss: 0.6086 - accuracy: 0.7525
Epoch 8/20
202/202 [==============================] - 0s 162us/sample - loss: 0.5895 - accuracy: 0.7673
Epoch 9/20
202/202 [==============================] - 0s 162us/sample - loss: 0.5698 - accuracy: 0.7822
Epoch 10/20
202/202 [========================

In [58]:
# Now with a couple more hidden layers in the next iteration.

# fix random seed for reproducibility
seed = 132
np.random.seed(seed)

# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(32, input_dim=13, activation='relu'))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=True)

# define the grid search parameters
param_grid = {'batch_size': [10],
              'epochs': [20, 30, 40, 50]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_2, y_2)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

Train on 202 samples
Epoch 1/20
202/202 [==============================] - 1s 3ms/sample - loss: 0.6539 - accuracy: 0.6535
Epoch 2/20
202/202 [==============================] - 0s 270us/sample - loss: 0.5986 - accuracy: 0.7624
Epoch 3/20
202/202 [==============================] - 0s 239us/sample - loss: 0.5482 - accuracy: 0.7723
Epoch 4/20
202/202 [==============================] - 0s 245us/sample - loss: 0.5037 - accuracy: 0.8020
Epoch 5/20
202/202 [==============================] - 0s 238us/sample - loss: 0.4627 - accuracy: 0.8020
Epoch 6/20
202/202 [==============================] - 0s 258us/sample - loss: 0.4436 - accuracy: 0.7970
Epoch 7/20
202/202 [==============================] - 0s 277us/sample - loss: 0.4361 - accuracy: 0.7921
Epoch 8/20
202/202 [==============================] - 0s 247us/sample - loss: 0.4173 - accuracy: 0.8020
Epoch 9/20
202/202 [==============================] - 0s 225us/sample - loss: 0.4093 - accuracy: 0.8267
Epoch 10/20
202/202 [========================

In [59]:
# With two additional layers it actually works best with 30 epochs. I bet we could continue this and and get a bit better with more layers,
# but I'll stop here for the sake of time...